version: 2
project_name: redis-inspector

before:
  hooks:
    - go mod tidy

builds:
  - id: redis-inspector
    main: ./cmd/redis-inspector
    binary: redis-inspector
    flags:
      - -trimpath
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
